version: "3"

services:
  web:
    build: ./docker-test-django
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./docker-test-django:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app: #3
    container_name: react-app-container #4
    image: node:14-alpine #5
    volumes:
      - ./reduxtk-app:/app #6
    working_dir: /app #7
    command: sh -c "npm install && npm start" #8
    ports:
      - "3000:3000" #9
    environment:
      - CHOKIDAR_USEPOLLING=true #10

